### ISSUE TITLE
Route discussion in exercise 3

### ISSUE THREAD

**Issue by GregDritschler** [IBM/cloudpakforapps-workshop#57]
I'm not sure what the following sentences in exercise 3 are talking about:

"Describing the route we can see it although it now exists, there is no path exposed by the proxy (which would be indicated by an annotation):"

"Give the route a path:"

There is something called path-based routing but that's got nothing to do with the haproxy.router.openshift.io/balance annotation.  That annotation affects balancing requests between the two registry pods.  I'm not sure why the IBM doc recommends it but I'm sure there's a good reason.  I think the text needs to be cleaned up to not refer to a "path" (or explain what you mean by "path" in this context).

Also note that there is a simpler way to add this annotation than using patch.

oc annotate route/docker-registry haproxy.router.openshift.io/balance=source

**Comment by henrynash** [comment]
Hi Greg, yeah, not that clear I agree - and we were indeed following the IBM docs....we'll re-examine this and see if we can simplify it.
